name: golf_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  geolocator: ^10.0.0
  shared_preferences: ^2.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/BirdieBoard.png
    - assets/images/loginbg.png
    - assets/images/titleImage.png
    - assets/images/registerbg.png

