// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSTqf-Agz6JGrD5S6tsw4i9cZbI2eCoVA',
    appId: '1:220069290015:web:61d637a03619f57f15352a',
    messagingSenderId: '220069290015',
    projectId: 'golf-app-3d9d1',
    authDomain: 'golf-app-3d9d1.firebaseapp.com',
    storageBucket: 'golf-app-3d9d1.firebasestorage.app',
    measurementId: 'G-65Z18W1FBZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY7Ml9nZVU84smdbMXooHqEroJphsdBCQ',
    appId: '1:220069290015:android:04277d6a5d2ae9b915352a',
    messagingSenderId: '220069290015',
    projectId: 'golf-app-3d9d1',
    storageBucket: 'golf-app-3d9d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEUUWxTetP5tI18LZ-B3P1niiFG7jeT2A',
    appId: '1:220069290015:ios:8e1bdf49ca96f8d715352a',
    messagingSenderId: '220069290015',
    projectId: 'golf-app-3d9d1',
    storageBucket: 'golf-app-3d9d1.firebasestorage.app',
    iosBundleId: 'com.example.golfApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEUUWxTetP5tI18LZ-B3P1niiFG7jeT2A',
    appId: '1:220069290015:ios:8e1bdf49ca96f8d715352a',
    messagingSenderId: '220069290015',
    projectId: 'golf-app-3d9d1',
    storageBucket: 'golf-app-3d9d1.firebasestorage.app',
    iosBundleId: 'com.example.golfApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSTqf-Agz6JGrD5S6tsw4i9cZbI2eCoVA',
    appId: '1:220069290015:web:15d3ebbeb7450fc215352a',
    messagingSenderId: '220069290015',
    projectId: 'golf-app-3d9d1',
    authDomain: 'golf-app-3d9d1.firebaseapp.com',
    storageBucket: 'golf-app-3d9d1.firebasestorage.app',
    measurementId: 'G-GXD1RZ8EN5',
  );

}