// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn0X5UivJl1i0ts149pHWKF9niG3rKy1U',
    appId: '1:245346920233:web:87ac1f9edb5ec7dbb37938',
    messagingSenderId: '245346920233',
    projectId: 'golf-app-for-4330',
    authDomain: 'golf-app-for-4330.firebaseapp.com',
    storageBucket: 'golf-app-for-4330.firebasestorage.app',
    measurementId: 'G-Q2NYDV4SYG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFETGyEtDCr4yB5kH4UB3YYoLH8wmHDX4',
    appId: '1:245346920233:android:4059ecf5eaca889fb37938',
    messagingSenderId: '245346920233',
    projectId: 'golf-app-for-4330',
    storageBucket: 'golf-app-for-4330.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASAJXcI-Qz8oXfCjZ_gKV2gxafarcaUlk',
    appId: '1:245346920233:ios:bcb6a09d0b4dec99b37938',
    messagingSenderId: '245346920233',
    projectId: 'golf-app-for-4330',
    storageBucket: 'golf-app-for-4330.firebasestorage.app',
    iosBundleId: 'com.example.golfApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASAJXcI-Qz8oXfCjZ_gKV2gxafarcaUlk',
    appId: '1:245346920233:ios:bcb6a09d0b4dec99b37938',
    messagingSenderId: '245346920233',
    projectId: 'golf-app-for-4330',
    storageBucket: 'golf-app-for-4330.firebasestorage.app',
    iosBundleId: 'com.example.golfApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAn0X5UivJl1i0ts149pHWKF9niG3rKy1U',
    appId: '1:245346920233:web:d265f880b24d86ecb37938',
    messagingSenderId: '245346920233',
    projectId: 'golf-app-for-4330',
    authDomain: 'golf-app-for-4330.firebaseapp.com',
    storageBucket: 'golf-app-for-4330.firebasestorage.app',
    measurementId: 'G-LRD20MVVG1',
  );

}