import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'frontend/screens/welcome.dart';
import 'frontend/screens/login.dart';
import 'frontend/widgets/nav_wrapper.dart'; // <-- wherever your NavWrapper is
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // auto-generated by CLI (explained below)

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  if (kIsWeb) {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } else {
    await Firebase.initializeApp();
  }

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Golf App',
      theme: ThemeData(
        primarySwatch: Colors.green,
      ),
      home: const WelcomeScreen(),
      routes: {
        '/login': (context) => const LoginScreen(),
        '/nav': (context) => const NavWrapper(),
      },
    );
  }
}
