name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3' # Flutter 3.16+ includes Dart 3.7

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze || true

      - name: Run tests
        run: flutter test || true
